version: '3.9'

services:
  db:
    build:
      context: .
      dockerfile: ./db.Dockerfile
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: ./app.Dockerfile
    restart: always
    # command: bash -c 'npm start dev'
    working_dir: /opt/app
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
    depends_on:
      - db
    volumes:
      - ./:/opt/app/

networks:
  default:
    name: node_postgres_network