version: '3.9'

services:
  db:
    container_name: db
    image: 259319778/nodejs2022q2-service_db
    restart: always
    build:
      context: .
      dockerfile: ./db.Dockerfile
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./:/opt/app/

  app:
    container_name: app
    image: 259319778/nodejs2022q2-service_app
    command: npm run start:dev
    build:
      context: .
      dockerfile: ./app.Dockerfile
    restart: always
    working_dir: /opt/app
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
    depends_on:
      - db
    volumes:
      - ./:/opt/app/

networks:
  default:
    name: node_postgres_network